spring:
  application:
    name: login

  datasource:
    url: jdbc:mysql://localhost:3306/parking
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddlAuto: update
config:
  api:
    parking:
      lot:
        url: http://localhost:8120/interface/authenticate
server:
  port: 8100